### ISSUE TITLE
Using Loom's runServer gradle tasks throws a runtime exception

### ISSUE THREAD

**Issue by TheLimeGlass** [KyoriPowered/adventure-platform-fabric#113]
```
 java.lang.RuntimeException: Error creating Mixin config adventure-platform-fabric.client.mixins.json for mod adventure-platform-fabric
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[?:?]
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config adventure-platform-fabric.client.mixins.json
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93) ~[fabric-loader-0.14.24.jar:?]
        ... 4 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'adventure-platform-fabric.client.mixins.json' was invalid or could not be read
        at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
        at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93) ~[fabric-loader-0.14.24.jar:?]
        ... 4 more
```
Using Fabric Adventure 5.9.0 and 1.20.1 MC (I need 1.20.1)

Using Loom's `gradlew clean runServer` instantly throws this issue.

My guess is because Adventure is expecting it to be like a traditional jar, where the Loom run tasks don't build a jar.

**Comment by zml2008** [comment]
Fixed in acac5bb, will be in 5.10.1.
