### ISSUE TITLE
Modded SoundCategory entries cause playSound to fail

### ISSUE THREAD

**Issue by qixils** [KyoriPowered/adventure-platform-fabric#115]
If any mod has created a custom `net.minecraft.sound.SoundCategory` (`class_3419`) then attempting to use `Audience#playSound` will cause an exception to be thrown. Example mods include [Noxesium](https://modrinth.com/mod/noxesium), [ExtraSounds](https://modrinth.com/mod/extrasounds). Here's a stacktrace from my mod crashing from [trying to use the method](https://github.com/qixils/minecraft-crowdcontrol/blob/f665d5527c8f55903bd54df5b1d111d67ff43b9e/fabric/src/main/java/dev/qixils/crowdcontrol/plugin/fabric/commands/ToastCommand.java#L79) with Noxesium installed:

```
java.lang.ExceptionInInitializerError
	at net.kyori.adventure.platform.fabric.impl.server.ServerPlayerAudience.playSound(ServerPlayerAudience.java:217)
	at net.kyori.adventure.audience.ForwardingAudience$Single.playSound(ForwardingAudience.java:352)
	at dev.qixils.crowdcontrol.plugin.fabric.commands.ToastCommand.lambda$executeImmediately$1(ToastCommand.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at dev.qixils.crowdcontrol.plugin.fabric.commands.ToastCommand.lambda$executeImmediately$2(ToastCommand.java:77)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Unmapped class_3419 element 'CORE_MUSIC_NOXESIUM!
	at net.kyori.adventure.platform.fabric.impl.MappedRegistry.checkCoverage(MappedRegistry.java:93)
	at net.kyori.adventure.platform.fabric.impl.MappedRegistry.<init>(MappedRegistry.java:78)
	at net.kyori.adventure.platform.fabric.impl.MappedRegistry$OfEnum.<init>(MappedRegistry.java:121)
	at net.kyori.adventure.platform.fabric.impl.MappedRegistry.named(MappedRegistry.java:54)
	at net.kyori.adventure.platform.fabric.impl.GameEnums.<clinit>(GameEnums.java:46)
	... 18 more
```

Confirmed on 5.5.2 and 5.10.1

**Comment by zml2008** [comment]
This is a vanilla enum, so mods messing with it is certainly a choice. I'd be fine downgrading missing mappings issues to a warning, and only throw a hard error in adventure-platform-fabric's own mod dev environment to ensure we don't miss mappings in our own update process.

**Comment by qixils** [comment]
Wontfix a critical function failure? I appreciate that adding onto vanilla enums is a questionable decision but to be clear A) *I* am not doing that, and B) I am not using them. The mere existence of these other mods is killing all sound in my mod because of some code that IMO should not exist in a production environment

**Comment by zml2008** [comment]
I mean, you'd get the exact same result if anyone ever used a switch expression on sound sources, it's not that wild

**Comment by kezz** [comment]
For reference, Noxesium will be removing the enum additions which will fix this issue.
